import type { Metadata } from 'next';
import localFont from 'next/font/local';

const geistSans = localFont({
    src: '../assets/fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: '../assets/fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const timestamp = new Date().getTime();
    return (
        <html lang="en">
            <head>
                <link
                    rel="stylesheet"
                    href={`/generated-styles.css?${timestamp}`}
                />
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                {children}
            </body>
        </html>
    );
}
